### ISSUE TITLE
希望增加循环数字的功能

### ISSUE THREAD

**Issue by dalphyx** [yoxjs/yox#12]
现在只能循环数组，当只是想循环输出指定个数的元素时，就有点繁琐了

**Comment by musicode** [comment]
给个用例？

**Comment by musicode** [comment]
现在还能循环对象

**Comment by dalphyx** [comment]
比如我写一个rate，根据传入的数字来循环显示对应的rate-item个数，现在我是在computed里创建出一个等长度的空数组来循环，效果是实现了，就是感觉有点繁琐

**Comment by musicode** [comment]
你来设计个语法？

**Comment by dalphyx** [comment]
功能上感觉使用现在的each就行，就是意思上差点

**Comment by musicode** [comment]
这个功能再说吧，等我或你有好的语法设计灵感。。

**Comment by musicode** [comment]
{{#each 0 -> 3}} 表示 0 1 2
{{#each 0 => 3}} 表示 0 1 2 3

@dalphyx 这个语法咋样？

**Comment by dalphyx** [comment]
挺好的，虽然我感觉只要下面那个就够了
