### ISSUE TITLE
ie8 select元素内含有循环生成的option时，提示对象不支持此属性或方法

### ISSUE THREAD

**Issue by dalphyx** [yoxjs/yox#13]
截图有点不方便，情景为我动态生成select的option，然后在model上绑定了一个value为‘’的一个属性，当初始化循环生成的option长度为0时，ie8下就报错在```var selectedOption = options[selectedIndex]```这一行提示对象不支持此属性或方法

**Comment by musicode** [comment]
ok，了解，最近我在做性能优化，等完成了一起修这个 bug

**Comment by musicode** [comment]
@dalphyx 重构了一版，你可以用 dist 目录下的试试

**Comment by dalphyx** [comment]
@musicode 额，没有在npm上发布新版本么

**Comment by musicode** [comment]
还没，非稳定版，怕有人用 cdn，直接就升级了。。

**Comment by musicode** [comment]
@dalphyx 有空反馈下结果哈

**Comment by musicode** [comment]
先关掉了，有问题再说

**Comment by musicode** [comment]
发布了 0.56.0 @dalphyx
