### ISSUE TITLE
each遍历数组，两层遍历时父下标不能更新

### ISSUE THREAD

**Issue by langlibaitiao** [yoxjs/yox#14]
https://jsfiddle.net/3jx6x8e1/32/
外层wrapper的下标fIndex，在内层list中初次遍历是正确的，在removeAt重新渲染视图后fIndex并没有更新

**Comment by musicode** [comment]
我看着没问题啊，你删掉是内层 list 的某一项，wrapper 的长度又不受影响

**Comment by langlibaitiao** [comment]
https://jsfiddle.net/3jx6x8e1/51/
sorry，demo重写未复现，是其他的问题，谢谢回答
