### ISSUE TITLE
像这样我怎么区分cbk

### ISSUE THREAD

**Issue by kelyljk** [yoxjs/yox#15]
`new Yox({
    el: '#app',
    template: '#template',
    data: {
        todos: [{
            "GysName": "A",
            "Cbk": false,
            "listcg": [
                { "GID": 1, "Cbk": false },
                { "GID": 2, "Cbk": true },
                { "GID": 3, "Cbk": true }
            ]
        },
                {
                    "GysName": "B",
                    "Cbk": false,
                    "listcg": [{
                        "GID": 4,
                        "Cbk": false
                    }]
                }
               ]
    }
});
`
`<div id="app"></div>
<script id="template" type="plain/text">
    <ul>
        {{#each todos:i}}
        <li>
        {{#each listcg:ii}}
            <div>{{GysName}}-{{i}}{{Cbk}}---{{GID}}-{{Cbk}}</div>
        {{/each}}
    </li>
        {{/each}}
    </ul>
</script>
<script src="https://unpkg.com/yox"></script>
`

**Comment by musicode** [comment]
这段有什么不对吗？

**Comment by kelyljk** [comment]
这个我通过改变最外面的那个字段来实现，但是还有个疑问 {{中能放函数么？ 还是只能过滤器？}}

**Comment by musicode** [comment]
取值的原则是从内到外，你在内层遍历时有 Cbk，外面的就取不到，还未支持指定层级取值

只能过滤器，或 data 里定义的函数

**Comment by kelyljk** [comment]
恩好的我知道了，谢谢

**Comment by musicode** [comment]
项目做完了跟我说说有啥建议哈
