### ISSUE TITLE
我又遇到一个问题 深度数组 第2层有更改了之后 dom层没有反应

### ISSUE THREAD

**Issue by kelyljk** [yoxjs/yox#16]
`  <div id="app"></div>
    <script id="template" type="plain/text">
        <div>
            {{#each it:i}}
            <div>
                <div><input type="checkbox" model="Cbks"> {{GysName}}</div>
                {{#each listcg:ii}}
                <input type="checkbox" model="Cbk"> {{GID}}---{{Num}}<button on-click="sub($keypath)">-</button><input type="text" model="Num"><button on-click="add($keypath)">+</button> {{/each}}
            </div>
            {{/each}}
        </div>
    </script>
 <script src="../dist/yox-legacy.min.js"></script>
    <script>
        var instance = new Yox({
            el: '#app',
            template: '#template',
            data: {
                it: [{
                    "GysName": "A",
                    "Cbks": false,
                    "listcg": [{
                        "Num": 1,
                        "Multiple": 24,
                        "GID": 6800,
                        "Cbk": false
                    }, {
                        "Num": 10,
                        "Multiple": 10,
                        "GID": 9857,
                        "Cbk": true
                    }, {
                        "Num": 10,
                        "Multiple": 10,
                        "GID": 10013,
                        "Cbk": true
                    }]
                }, {
                    "GysName": "B",
                    "Cbks": false,
                    "listcg": [{
                        "Num": 1,
                        "Multiple": 24,
                        "GID": 17739,
                        "Cbk": false
                    }]
                }]
            },
            methods: {
                add: function(keypath) {
                    console.log(keypath);
                    var tt = this.get(keypath);
                    tt.Num = parseInt((tt.Num + tt.Multiple) / tt.Multiple) * tt.Multiple;
                    this.set(keypath, tt);
                    console.log(JSON.stringify(this.get('it')));
                },
                sub: function(keypath) {
                    console.log(keypath);

                }
            }
        });

        // console.log(1)
    </script>`

**Comment by musicode** [comment]
你能有个正常排版么。。

**Comment by kelyljk** [comment]
他会自动的转化 我晕了

**Comment by musicode** [comment]
那就写个能跑的 demo，发个链接

**Comment by kelyljk** [comment]
http://doui.vip/list1.html

**Comment by kelyljk** [comment]
你看下log输出，是不是我漏看了文档

**Comment by musicode** [comment]
因为你改的是引用类型，改了属性之后 set 回去，内部不知道你变了

正确的方式如下：

```js
var data = this.copy(this.get(keypath));
你的改动
this.set(keypath, data);
```

**Comment by kelyljk** [comment]
好的，谢谢
