### ISSUE TITLE
数组的深度监听

### ISSUE THREAD

**Issue by kelyljk** [yoxjs/yox#18]
你好，监听 vue有深度监听 请问yox 怎么实现

**Comment by musicode** [comment]
```js
{
    watchers: {
         '**': function () {

         }
    }
}
```

文档里写了这部分

**Comment by kelyljk** [comment]
** 是监听的哪个变量呢？
比如 我data中有个 it 的数组 想监听它的变动，当深度被改变的时候 怎么弄

**Comment by kelyljk** [comment]
**的写法我是看到的，但是表示没懂。**是表示监听所有的变量么？

**Comment by musicode** [comment]
那就监听 it.**

**Comment by kelyljk** [comment]
好 我试试

**Comment by kelyljk** [comment]
实现了。太强大了，哈哈  我在demo中看见还有1个*的 那是代表什么

**Comment by musicode** [comment]
啥东东？

**Comment by musicode** [comment]
哦，去看 glob 语法，这不是我发明的

**Comment by kelyljk** [comment]
看到了，
此外，我们还非常人性化的支持了通配符，这个特性类似于磁盘路径中的 glob，如下：
*：匹配一个段
**：匹配任意长度的段
我们用几个例子加深印象：
user.*：匹配 user 的任意属性，如 user.name、user.age，但无法匹配 user.name.familyName
user.**：匹配 user 的任意属性，且不限深度
users.*.name：可以匹配 users.0.name、users.1.name 等，但无法匹配 users.name
users.**.name：只要 keypath 以 users. 开头，以 .name 结尾就能匹配
**：超级无敌的存在，可以匹配任意 keypath，且不限深度
我得认真看一遍这个，哈哈 谢谢

**Comment by musicode** [comment]
跟 vue 比咋样啊

**Comment by kelyljk** [comment]
从大框来说 差不多，但是兼容vue肯定没法比，而且yox 更轻量，对原有的页面改造更适用，就是有一点this.set 和this.get 是异步的操作，在一些代码的书写上需要注意点，之前我就遇到过在循环外面set一个值，在循环里面又去set值时会出现时间上的一些交差，也许是我个人写法问题，还有事件和方法，我之前是vue写的 方法后面可以不加（），但是这边不加（）会变成事件是一个需要注意的，还有{{}}中只能过滤器，虽然过滤器也是方法，但是用起来跟vue的概念还是有点不同的

**Comment by kelyljk** [comment]
要是有时间 建议您 可以写个和vue的差异，这样会帮助懂vue的人更快的熟悉yox，

**Comment by musicode** [comment]
哪里用的奇怪一定要跟我说

**Comment by musicode** [comment]
set 和 get 不是异步啊，为啥你会这么说

**Comment by kelyljk** [comment]
恩好的，今天已经基本都摸索过了，我项目的一个页面 已经使用yox 打算跟项目其他成员交流下，接下来的项目 估计可以大范围的使用yox
// 因为是异步更新视图
// 使用单个设值还是批量设值请随意，不影响性能

**Comment by musicode** [comment]
vue 也是异步更新视图，这点一样的

**Comment by kelyljk** [comment]
这边的异步只是更新视图有关么？

**Comment by musicode** [comment]
是的

**Comment by kelyljk** [comment]
对了 还有一个 刚刚在写的时候 比如 使用Yox.array.each之后 里面this不能用 这是正常的 但是 我在外部定义了一个el  在内部使用 却不行的 我定义其他的就可以 是不是因为el是yox的变量问题？

**Comment by musicode** [comment]
没懂

**Comment by kelyljk** [comment]
这是个方法
  fjcbk: function(oldValue, keypath) {
                    // this.set(keypath + ".Cbks", !oldValue);
                    var el = this;
                    Yox.array.each(this.get(keypath + '.listcg'), function(tt, i) {
                        el.set(keypath + '.listcg.' + i + '.Cbk', !oldValue);
                    });
                },

**Comment by musicode** [comment]
这样没问题啊

**Comment by kelyljk** [comment]
但是我就是这样报错的，我不知道是不是因为我其他的写法产生的问题，等下我写个demo 复现下 发你

**Comment by kelyljk** [comment]
http://doui.vip/list1.html 你看下， 9857前面的勾去掉，然后勾6800

**Comment by kelyljk** [comment]
我忽然发现一个问题，我的循环当中定义了i。也许是这个原因 我晕死

**Comment by musicode** [comment]
我说嘛，这种问题框架不太可能出现了
