### ISSUE TITLE
使用ie8打开

### ISSUE THREAD

**Issue by kelyljk** [yoxjs/yox#20]
http://doui.vip/list1.html
比如《span》{{GID}}《/span》 ie8上不显示

**Comment by kelyljk** [comment]
《span》《/span》标签中 《p》《/p》

**Comment by musicode** [comment]
![image](https://user-images.githubusercontent.com/2732303/38003991-c1fda68e-326c-11e8-9b8b-64ba3d930290.png)

**Comment by kelyljk** [comment]
你这是什么调试工具？ 
![image](https://user-images.githubusercontent.com/10511872/38004542-47ec9398-326f-11e8-82c0-5e61e44372f8.png)

**Comment by kelyljk** [comment]
这个调试工具 有没有下载地址？还是你们公司内部的？

**Comment by musicode** [comment]
我用的是 win10 里的 360 ...

**Comment by musicode** [comment]
这不就是正常的 js 么，有啥不行的

**Comment by kelyljk** [comment]
如果data 一开始有值可以，但是后续给it 赋值 页面没反应

**Comment by kelyljk** [comment]
http://doui.vip/list1.html 可以通过这边查看

**Comment by musicode** [comment]
你那样肯定是不行的，初始化可以 data: data，后续的修改都必须是 set
