### ISSUE TITLE
技术文档错别字？

### ISSUE THREAD

**Issue by fengma1992** [yoxjs/yox#23]
![image](https://user-images.githubusercontent.com/6904899/41136702-02649a0e-6b0a-11e8-8923-dbc2f62fcf04.png)
指令》事件节流  章节里面，‘直觉’还是‘自觉’？

不知道疑似错别字能不能提issue     ：）

**Comment by musicode** [comment]
确实写错了，谢谢提醒，学习过程中有啥不爽么
