### ISSUE TITLE
有关于对象循环的问题

### ISSUE THREAD

**Issue by IMAXfun** [yoxjs/yox#25]
想请问下我用一个modelmap包装的一个List<entity> list   这个${list}在yoxjs中应该怎么处理

**Comment by musicode** [comment]
具体点

**Comment by IMAXfun** [comment]
具体的就是有一个List<entity> list  然后通过 modelMap.addAttribute("list",list);  返回到页面上,   页面上就有了一个${list}  ,想把这个list里面的值传到select里面的option ,但是在yox中的data里  不知道怎么处理这个${list}

**Comment by musicode** [comment]
https://github.com/yoxjs/yox/blob/master/example/binding.html#L197  看这个

**Comment by IMAXfun** [comment]
大佬,不好意思 我前端知识比较弱  麻烦您解答一下 data里面的selecteduser应该是从user里面选中的值,那么user里面 应该就是循环到option的值 ,我现在的疑问是我那个${list}放在user里面是应该怎么处理,我尝试过了user:'${list}'    user:['${list}']的写法  但是应该都不对,是要在user:[each(${list})]循环一下吗?
