### ISSUE TITLE
对于multiple属性的多选select，不支持双向绑定

### ISSUE THREAD

**Issue by Ryutaku** [yoxjs/yox#26]
对于支持多选 的select，比如:

<select multiple model='ids'>
<option value="1">张三</option>
<option value="2">李四</option>
<option value="3">王二</option>
</select>

当多选时，
发现无法实现双向绑定，ids始终只能绑定一个值，麻烦作者核实一下。

**Comment by Ryutaku** [comment]
`<select multiple model='ids'>
<option id="1"> 张三</option>
<option  id="2"> 李四</option>
<option  id="3"> 王二</option>
</select>`

**Comment by musicode** [comment]
这个确实还没支持，现在用 select 做多选还多么？应该用自定义组件会好些吧

**Comment by Ryutaku** [comment]
bootstrap-select，这种支持多选的select组件用得还是挺多的

**Comment by musicode** [comment]
我先评估一下改动量，进度会在这说

**Comment by Ryutaku** [comment]
OK，i'm here waiting for you.

**Comment by musicode** [comment]
不要搞得辣么暧昧

**Comment by musicode** [comment]
这两天忙，刚修复了 yox@0.62.7

**Comment by Ryutaku** [comment]
非常感谢！

**Comment by musicode** [comment]
有啥建议或意见么？或谈谈使用体验呢？

**Comment by Ryutaku** [comment]
我一直比较疑惑yoxjs监听和计算属性的区别，论使用便利性而言，监听似乎更好用，因为计算属性对于多层次的对象属性的变动必须指定依赖，而监听呢，一个类似的user.**就完事了。从这个使用角度，若要实现计算属性类似的功能的话，我更倾向于在watchers里实现。

体验方面：兼容ie8非常nice，使用过程中非常愉快，比vue轻量，语法简单得不能再简单，不像vue那样各种语法糖，讲真，我到现在都不知道vue的绑定class应该用哪种方式写，每次用到动态绑定class我都得查文档。而yoxjs的语法基本上看一遍就知道咋回事了，简单单一，这一点yoxjs真是贴心啊，完全秒杀vue。

目前还未将yoxjs使用在大数据量的场景上，性能问题暂时没有遇到，在使用过程中遇到问题我会在这里及时反馈。

**Comment by musicode** [comment]
监听其实是底层机制，计算属性只是为此暴露出来的便利接口而已。

从语义上说，计算属性其实有场景，比如全选的那个例子，它有 get/set 的概念，但它又不是某个具体的属性，是个虚拟的需要计算的属性。

性能问题，可能也是我不想大规模推广的原因了，因为我确实不知道会不会有性能问题，不敢乱做广告说秒杀 vue 多少条街，其实 yox 是比 vue 慢的，因为简易的语法需要付出代价。

但应该不至于慢的能感觉出来，如果那样，我自己也受不了啊...
