### ISSUE TITLE
IE 环境下，multiple select 只能单向绑定？

### ISSUE THREAD

**Issue by Ryutaku** [yoxjs/yox#27]
multiple select 在chrome双向绑定都无问题，但在ie 环境下，只支持从数据到视图的单向绑定。视图中select的选项改变，并没有改变数据模型。

请核实。

**Comment by Ryutaku** [comment]
ie的各版本下均有此问题

**Comment by musicode** [comment]
难道 IE 不支持 select.selectedOptions 么...

**Comment by Ryutaku** [comment]
浏览器支持
所有浏览器都支持 selected 属性。

**Comment by musicode** [comment]
select 元素的 selectedOptions 属性有么？我是通过它获取选中项的，如果这个都不支持，那只能遍历所有 option 了....

**Comment by Ryutaku** [comment]
试了下，在ie环境下，取selectedOptions时，获取的结果是undefined
