### ISSUE TITLE
关于keypath

### ISSUE THREAD

**Issue by cnwhy** [yoxjs/yox#3]
有没有考虑这种奇葩数据
{
“a.b”:1,
a:{b:2}
}
如果你要把你的框架放出来给大家用的话，这种有坑的情况应该是要解决的，毕竟人家的数据是符合规范的。
单元测试不可少，不然不敢用呐。

**Comment by musicode** [comment]
这个例子不知你觉得应该如何处理？

**Comment by cnwhy** [comment]
我觉得是这样，不需要改变现有以 ‘.’ 分隔的默认行为。
只是要使用者在知道这个情况后，至少要有解决方案。
比如keypath支持 '["a.b"]'这种，或者，get,set的第一次参数支持数组。
至于数据模版里可能要另想办法了

**Comment by musicode** [comment]
keypath 这种东西我用了一年多，还没碰到这种 case，技术方案有时候也要考虑是不是真的会有这种情况，比如 virtual dom 只是同级比较，那你不能说，你怎么不管跨级呢？如果要管，virtual dom 就没法做了

**Comment by musicode** [comment]
现在的情况应该是 get('a.b') 优先读 'a.b'，如果要读对象里的 b，用 get('a').b
