### ISSUE TITLE
吐槽

### ISSUE THREAD

**Issue by lcoder** [yoxjs/yox#31]
![image](https://user-images.githubusercontent.com/5225853/60479539-bec4e100-9cb8-11e9-9df9-e5ba69d880cb.png)

绝对必要，那是作者你的场景没遇到而已

场景一，做markdown转vue组件时候，出现了冲突问题
![image](https://user-images.githubusercontent.com/5225853/60479978-6a226580-9cba-11e9-96db-373beb4a4899.png)

场景二，别人做开源的态度
[vue就不多说了，markdown解析器，别人家都照顾到了这个需求](https://github.com/arve0/markdown-it-attrs/issues/80)

**Comment by musicode** [comment]
单个 {  或 } 我也不会解析，只有 {{ 或 }} 这样的才会被特殊对待。

你说的 markdown 转 vue 我确实没遇到过，不过我没看懂具体啥意思，markdown 里面有 {{ 和 }} ？？

**Comment by musicode** [comment]
还有你看的文档是 0.x，建议看新版本文档

**Comment by musicode** [comment]
我不让定制的原因很简单，我希望所有 yox 项目风格保持一致

**Comment by lcoder** [comment]
> 单个 { 或 } 我也不会解析，只有 {{ 或 }} 这样的才会被特殊对待。
> 
> 你说的 markdown 转 vue 我确实没遇到过，不过我没看懂具体啥意思，markdown 里面有 {{ 和 }} ？？

单个{ 的情况，我想说明的是，开源，要照顾意想不到的场景
markdown里有`{{`，是我要做md文档转vue组件的一个webpack-loader的场景。里面的内容和vue的插值语法冲突

**Comment by musicode** [comment]
我还是没看懂，因为 md 里有 {{ }}，所以你想换成别的，比如配置为 {{{{  或 }}}}，是这个意思吗？

是用于 demo 展示吗？

**Comment by musicode** [comment]
我只是想确认一件事，这个场景具体是把 {{ }} 替换成什么？

技术上这都不是问题，我可以提供一个配置项，随便你改啥都行

**Comment by musicode** [comment]
我跟你的想法不同，我不希望太多扩展，我怕这个框架失控，我要审核每一个新功能是不是值得对外开放，这是我的态度
