### ISSUE TITLE
加油作者，问一个关于依赖路径的问题

### ISSUE THREAD

**Issue by jinyang1994** [yoxjs/yox#33]
我读了一点点的源码。发现了一个地方
```javascript
import {
  Watcher,
} from '../../../yox-type/src/type'
```
引用路径为什么要这样写？
我可以默认开发的时候需要把对应所有的`yox-`开头的库按照这种结构整理一下嘛？
或者说作者有什么别的考虑是我没想到的

**Comment by musicode** [comment]
路径的问题是因为我本地是这样的结构

```js
yoxjs/
   yox/
   yox-type/
   yox-common/
   yox-observer/
   yox-xxx
```

为了避免频繁的 npm publish yox-xx，我就这么写路径了，反正能用 rollup 成功构建出来，tsc 也能正常编译，何乐而不为

**Comment by deepred5** [comment]
可以试试用lerna管理包

**Comment by musicode** [comment]
@deepred5 好的，我也是被喷了之后才第一次听说这东西，会去试试，谢谢了
