### ISSUE TITLE
Issue with babel-preset-env

### ISSUE THREAD

**Issue by prichodko** [yoxjs/yox#4]
Hey @musicode, I tracked you problem with the babel-preset-env.

I cloned your repository and tried to run it locally. Although the rollup was configured correctly, you were right, that it still throw a module transformer error. Problem **is not** in rollup and it's config. Problem lies in the packages you are using internally. Namely `yox-common`, `yox-expression-compiler`, `yox-observer` and `yox-template-compiler`, they all specify it's custom .babelrc file with **babel-preset-es2015**, which causes ES6 module transformation, when I deleted all the .babelrc files, I was able to build the library successfully.

Although I don't really understand the reason behind specifying .babelrc in each package, but as a solution a propose specifying a `module` field in each `package.json` pointing to a root file, since your packages are already written using ES6 modules. You can read more about it here - https://medium.com/webpack/webpack-and-rollup-the-same-but-different-a41ad427058c

Hopefully it helps.

**Comment by musicode** [comment]
@prichodko 

Many many thanks to you!

As you suggest, I add `.babelrc` into `.npmignore` file under `yox-*` projects.

Thank you~

**Comment by prichodko** [comment]
Did it work? If so, feel free to close the issue.

**Comment by musicode** [comment]
yes
