### ISSUE TITLE
on-click问题

### ISSUE THREAD

**Issue by yongsheng-kiki** [yoxjs/yox#41]
` <li class="car pull_left in_border relative_pos"
                            on-click="carCheck($event,computedDatas[index])" style="height: 133px;padding-right: 0;">
                            <i class="iconfont absolute_pos car_check"><span hidden>{{id}}</span></i>
                            <div style="height:100%">
                                <p>
                                    <span style="width: 60px;display: inline-block;text-align: right">状态：</span>
                                    {{#if status==1}} <span>启用</span>{{/if}}
                                    {{#if status==0}}<span >禁用</span>{{/if}}
                                </p>`
我给li绑定了on-click事件，可是他会穿透到下面的i ，p等元素，如何阻止呢，因为我想只点击li的时候才执行

**Comment by musicode** [comment]
这是 dom 事件本身的特性，你可以判断 event.originalEvent.target 为 li 再处理
