### ISSUE TITLE
dblclick

### ISSUE THREAD

**Issue by yongsheng-kiki** [yoxjs/yox#42]
为啥我绑定on-dblclick双击事件，单击的时候也触发呢？该如何阻止单击事件

**Comment by musicode** [comment]
这是浏览器的行为吧，yox 事件模块没有处理过这种逻辑，如果你要判断，可以读取 `event.originalEvent.type`

**Comment by yongsheng-kiki** [comment]
可是为啥原生绑定ondblclick则不会触发单击事件呢

**Comment by musicode** [comment]
我这测试是会触发两次 click，再触发 dbclick

**Comment by yongsheng-kiki** [comment]
我发现传入$event以后不用判断也是双击才会触发双击事件，谢谢大佬的回复

**Comment by musicode** [comment]
没事，总之我没有写特殊逻辑，一切随浏览器
