### ISSUE TITLE
字符串如何支持换行符<br/> 

### ISSUE THREAD

**Issue by tanranran** [yoxjs/yox#43]
如题？找了很久文档都没有发现

**Comment by musicode** [comment]
模板 - 危险插值

```html
<div>
  {{{html}}}
</div>
```

**Comment by tanranran** [comment]
如果危险差值附近里面存在if语句，那么不会渲染成HTML而是会成为TXT
`<div>
  {{{'<b>aaaaa</b>'}}}
  {{#if xxx==0}}
  {{{'<b>bbbbbb</b>'}}}
  {{/if}}
</div>`

**Comment by musicode** [comment]
文档里写了这种情况哈
