### ISSUE TITLE
文档给出的代码无法运行

### ISSUE THREAD

**Issue by iamcer** [yoxjs/yox#49]
在文档中的案例是无法运行的，这很打击刚接触的人。
`直接复制一下代码运行报错：
 `<div id="app"></div>
<script id="template" type="text/plain">
	<div>
    name: {{name}} <br>
    version: {{version}}
  </div>
</script>`

![image](https://user-images.githubusercontent.com/26667927/96999141-49dd8080-1567-11eb-85da-90dcb18e1dfa.png)
报错信息：**yox.esm.js:1038 Uncaught Error: [Yox fatal]: The "template" option should have just one root element.**

**Comment by musicode** [comment]
[这个](http://jsrun.net/YxyKp/edit) 是能运行的吧
