### ISSUE TITLE
在computed中set一个属性后，就无法在其他方法中再更改了

### ISSUE THREAD

**Issue by dalphyx** [yoxjs/yox#5]
link: https://jsfiddle.net/3jx6x8e1/6/

我在computed属性中set了一个属性值，这时候在事件中改变这个属性无效。这点跟Vue有所差异。

**Comment by musicode** [comment]
你没用到 test 这个计算属性，为啥你认为那个函数会执行呢

**Comment by dalphyx** [comment]
对啊，我没用到test但是它却执行设置了testVal值为2，我点击执行method也无法把testVal设置为3，移除掉这个computed属性后，点击是正常的

**Comment by musicode** [comment]
确实是个 bug，我修一下，多谢反馈

**Comment by musicode** [comment]
@dalphyx 已修复
