### ISSUE TITLE
开源项目问题？

### ISSUE THREAD

**Issue by simplesux** [yoxjs/yox#52]
最近在看楼主开源的项目源码，在看到很早楼主开源过gui框架，对里面架构觉得比较新奇，请教下，楼主开发的灵感来自于哪，或者说那些库，谢谢解答

**Comment by musicode** [comment]
你该不会为了问个问题，专门注册了 Github 吧...

那个项目太早了，我都有点忘了，应该是刚入行看到一些公司大佬写的库，加上自己的一些改进，才会有那种尝试，后面发现想法不成熟，早就不维护了。

**Comment by simplesux** [comment]
但是感觉思想很超前呀！强，后续准备研究下yox

**Comment by musicode** [comment]
那个年代，前端太蛮荒了，啥也没有，都是瞎尝试，不像现在，格局都定下来了，新人其实也没啥好发挥的

**Comment by simplesux** [comment]
确实是这么回事，话说能加楼主个wx好友吗？

**Comment by musicode** [comment]
不加了，不瞎聊，我也挺忙的..
