### ISSUE TITLE
ie8下模板渲染失败

### ISSUE THREAD

**Issue by liu419249629** [yoxjs/yox#53]
渲染效果成 data="xxx"

`<DIV id=app><DIV data="模板文字"></DIV></DIV>`

**Comment by liu419249629** [comment]
代码如下：
`export default {
  template: `
  <div>
    模板文字
  </div>
`,
  data: {
    xx: 'testxx'
  },
  methods: {
    testxx: function() {
      alert(2333)
    }

  }

}
`

**Comment by liu419249629** [comment]
```

export default {
  template: `
  <div>
    模板文字
  </div>
`,
  data: {
    xx: 'testxx'
  },
  methods: {
    testxx: function() {
      alert(2333)
    }

  }

}

```

**Comment by liu419249629** [comment]
webpack+es3 plugin 搭建的

**Comment by musicode** [comment]
第一段还是第二段？你看了文档里关于如何兼容低版本 IE 的章节么？

**Comment by liu419249629** [comment]
是使用legacy下的目录。用babel作了转换，没有报错

**Comment by liu419249629** [comment]
![20210903165419](https://user-images.githubusercontent.com/17897624/131978742-f6199c49-cea1-4003-9e2a-afd2a0332234.jpg)

**Comment by liu419249629** [comment]
![20210903165419](https://user-images.githubusercontent.com/17897624/131978839-208356f5-98c5-421d-8943-73cffe06ea7e.jpg)

这个是IE9下面，上图是IE8下面

**Comment by musicode** [comment]
这不是渲染出来了么？问题在哪？

**Comment by liu419249629** [comment]
ie9渲染出来了，ie8渲染出不来。只是把div中间的元素，附加到data上面了。

**Comment by musicode** [comment]
模板就是下面这段吗？
```
<div>
    模板文字
  </div>
```

**Comment by liu419249629** [comment]
是的，然后被渲染成html
```
<div id=app><div data="模板文字"></div></div>
```

**Comment by musicode** [comment]
复现有点困难，主要是手头没有装了 IE8 系统，如复现问题，我会改

**Comment by musicode** [comment]
yox@1.0.0-alpha.222  已修复
