### ISSUE TITLE
ie8会提示 “缺少标识符、字符串、或数字”

### ISSUE THREAD

**Issue by kangqiangzj** [yoxjs/yox#59]
SCRIPT1028: 缺少标识符、字符串或数字

麻烦指导一下，谢谢

**Comment by musicode** [comment]
先参考 https://yoxjs.github.io/yox/#/ie，如果这样还不行，再来反馈问题，最好有报错截图

**Comment by kangqiangzj** [comment]
> 先参考 https://yoxjs.github.io/yox/#/ie 如果这样还不行，再来反馈问题，最好有报错截图
我使用的是您给的example目录下的binding.html做的测试，改了下yox文件引用，页面代码和报错截图如下：
页面代码：
![image](https://user-images.githubusercontent.com/34061174/199391451-cf1030b4-f394-47d7-97da-f06479b3ae5a.png)
报错截图：
![image](https://user-images.githubusercontent.com/34061174/199391517-7ca47eb9-6688-4bcb-99ce-ae41d8faf1b9.png)
浏览器版本：
![image](https://user-images.githubusercontent.com/34061174/199391593-5c2797c7-5f89-42da-92ae-88f19798777d.png)

**Comment by kangqiangzj** [comment]
这个是代码，辛苦指导
[yox-test.zip](https://github.com/yoxjs/yox/files/9916395/yox-test.zip)

**Comment by musicode** [comment]
![WX20221102-125806@2x](https://user-images.githubusercontent.com/2732303/199401886-d0c96981-7551-43fe-9717-0256c9dd7837.png)
点下这里，截图看下

**Comment by kangqiangzj** [comment]
![image](https://user-images.githubusercontent.com/34061174/199410428-ca130b23-c53d-4fab-9194-b028e504d5e1.png)

**Comment by kangqiangzj** [comment]
上面是报错点进去的之后的截图，谢谢。

**Comment by musicode** [comment]
查到问题了，过两天会修复，你可以先在chrome开发

**Comment by kangqiangzj** [comment]
> 查到问题了，过两天会修复，你可以先在chrome开发

好的，修复好了麻烦告知一下，我们这边生产上测出的这个问题。谢谢

**Comment by kangqiangzj** [comment]
请问我项目上的话，有临时处理方案吗

**Comment by musicode** [comment]
我今晚发一版吧，发完会在这通知你

**Comment by kangqiangzj** [comment]
行，谢谢

**Comment by musicode** [comment]
yox@1.0.0-alpha.402 已修复

**Comment by musicode** [comment]
@kangqiangzj 使用新版本后反馈一下情况哈

**Comment by kangqiangzj** [comment]
好的，辛苦

**Comment by kangqiangzj** [comment]
@musicode 新版本没有问题 赞
