### ISSUE TITLE
yoxjs 与 layui upload的整合问题

### ISSUE THREAD

**Issue by sbty1212** [yoxjs/yox#60]
代码如下:
 
![image](https://user-images.githubusercontent.com/26788415/199469805-8a38745c-8f3d-4c5d-ab7b-e55f0ef62b18.png)
![image](https://user-images.githubusercontent.com/26788415/199469876-e860319f-74fd-4c2d-871e-1d72b23049b4.png)

界面如下:
![image](https://user-images.githubusercontent.com/26788415/199464450-9fbac22c-d962-4c41-bd60-60403ae11611.png)
问题 如下:
点击添加按钮  界面可以 新增 但是 上传无法弹出 文件选择框
下面是 layui upload 初始化代码
![image](https://user-images.githubusercontent.com/26788415/199470081-6f47b83a-ff74-43d4-8f12-a731b212f503.png)
 下面是 添加操作的代码
![image](https://user-images.githubusercontent.com/26788415/199470275-cffd8c76-f22a-4d5e-916f-44bf2dd23c65.png)

怎么解决??

**Comment by musicode** [comment]
这样没缩进的代码怎么看呢？

**Comment by sbty1212** [comment]
问题简单点 说 就是  yoxjs  使用  this.append('nodes',this.get('onenode')) 增加 数据后 视图更新了 但 upload 控件无法初始化

**Comment by sbty1212** [comment]
layui.use('upload', function(){
                var upload = layui.upload;
                upload.render({
                    elem: '.uploadlinks'
                    ,url: '<?php echo Yii::$app->params['imageUploadUrl']?>'
                    ,done: function(data){
                        var item = this.item;
                        current_index = $(item).attr("index");
                        //上传完毕回调
                        if (data.ret == 200) {
                            if(data.data.code==0){
                                var url = data.data.url;
                                vm_uploadlinks.set('nodes.'+current_index+'.value',url);
                            }else{
                                alert(data.data.msg);
                            }
                        }
                    }

                });
            });

**Comment by sbty1212** [comment]
进页面后 是 afterMount: function () {} 这个 初始化 upload 控件的

**Comment by sbty1212** [comment]
需要 再次 初始化 upload 控件  就不知道 在哪里 初始化了

**Comment by musicode** [comment]
这样子的排版，我看不懂你的代码在写什么

**Comment by sbty1212** [comment]
复制文字没排版 直接 上传图片了
帮忙看下 谢谢

**Comment by musicode** [comment]
layui这个组件初始化成功了么？特别是 .uploadlinks 是个啥，有这个元素么，如果有，upload组件创建成功了么

**Comment by musicode** [comment]
最好不要这样初始化 dom 组件，应该用一个 Yox 组件封装你这个 layui 组件，外面再用 Yox 组件，参考下文档关于组件的部分

**Comment by musicode** [comment]
这个 issue 跟 yox 没啥关系，按你的思路，vue 估计也有这个问题
