### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by dalphyx** [yoxjs/yox#7]
link: https://jsfiddle.net/3jx6x8e1/8/

情景：异步调用数据并赋值，渲染的内容由一个自定义组件包裹，随后报错。

**Comment by musicode** [comment]
这个 bug 我得先想想怎么改比较好

**Comment by musicode** [comment]
发了新版本

**Comment by musicode** [comment]
@dalphyx 你是打算用这个框架么？

**Comment by dalphyx** [comment]
@musicode 额。。某个蛋疼项目需要支持ie8

**Comment by musicode** [comment]
赞，你就是目标用户啊，哈哈

**Comment by dalphyx** [comment]
@musicode 懒得开issue，问个问题，子组件怎样引用直接父组件，比如我tab-pane想引用包含他的tab-container组件，看了下现在子组件的parent全是根组件

**Comment by musicode** [comment]
没法引用，这样的逆向引用是反模式，用事件吧

**Comment by dalphyx** [comment]
@musicode 行，我试试，本来以为把之前的vue组件直接稍微简单改写下就好了

**Comment by musicode** [comment]
vue 咋写的？我好久没用 vue，忘的差不多了。。

**Comment by musicode** [comment]
简单改肯定是不行的，我只是抄了 vue 的轮廓设计，对细节一点没抄，完全是按我的开发习惯来设计的

**Comment by dalphyx** [comment]
恩。现在暂时发现子组件没法引用直接父组件比较蛋疼，需要一定的改写工作量，其他的都还好

**Comment by musicode** [comment]
@dalphyx 最新版本，组件能通过 `$parent` 属性取到父组件了

**Comment by dalphyx** [comment]
@musicode 好的，不过升级的时候报component.set()处有问题，具体原因是啥没去找，可以看看。

**Comment by musicode** [comment]
今天发的最新版没这个问题
