### ISSUE TITLE
监听events只能获取到类型为对象的数据

### ISSUE THREAD

**Issue by dalphyx** [yoxjs/yox#8]
比如this.fire('test',  1)就无法取到1这个值

**Comment by musicode** [comment]
```js
events: {
    test: function (event, data) {
         // data 是 1
    }
}
```

**Comment by dalphyx** [comment]
额，就是因为取不到啊，包装成this.fire('test', { id: 1})就能取到{id: 1}这个数据了

**Comment by musicode** [comment]
哦，对，只能是对象。。

**Comment by musicode** [comment]
为了统一格式，避免团队合作时出错

**Comment by dalphyx** [comment]
这个强约束不好吧，而且文档里也没写来着，试了好久

**Comment by musicode** [comment]
强约束是对象是有必要的，文档我补一下。。

**Comment by musicode** [comment]
[事件流](https://musicode.gitbooks.io/yox/%E4%BA%8B%E4%BB%B6%E6%B5%81.html)
