### ISSUE TITLE
数据响应问题

### ISSUE THREAD

**Issue by dalphyx** [yoxjs/yox#9]
link: https://jsfiddle.net/3jx6x8e1/11/

**Comment by musicode** [comment]
test 这个父对象没变化，不会去 diff 他的子属性

**Comment by dalphyx** [comment]
@musicode  那我现在想要单独改变某个属性发现无法响应该怎么解决呢

**Comment by musicode** [comment]
this.set('test.a', 1);

**Comment by dalphyx** [comment]
@musicode https://jsfiddle.net/3jx6x8e1/12/  那这种情况算bug么

**Comment by musicode** [comment]
不算，因为你 set 的时候，那个值就是 2 了，没变
